### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by redbox2000** [xcir/varnishHostStat#11]
Hi 
In case of centos6 latest, the several error messages are displayed.

varnishhoststat.py[5107]: Traceback (most recent call last):
  File "varnishhoststat.py", line 7, in main
    vhs = varnishhoststatcore.varnishHostStat(opts)
  File "/root/src/varnishHostStat-master/varnishhoststatcore.py", line 69, in __init__
    self.vap     = varnishapi.VarnishLog(vops)
  File "/root/src/varnishHostStat-master/varnishapi.py", line 416, in __init__
    VarnishAPI.__init__(self,sopath)
  File "/root/src/varnishHostStat-master/varnishapi.py", line 321, in __init__
    self.lva     = LIBVARNISHAPI13(self.lib)
  File "/root/src/varnishHostStat-master/varnishapi.py", line 195, in __init__
    self.VSL_CursorFile         = lib.VSL_CursorFile
  File "/usr/lib64/python2.6/ctypes/__init__.py", line 366, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib64/python2.6/ctypes/__init__.py", line 371, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/varnish/lib/libvarnishapi.so.1: undefined symbol: VSL_CursorFile

What does it means ? the python version issue?

Best

**Comment by xcir** [comment]
Please tell me your
- Varnish Cache version
- varnishHostStat version
- varnishHostStat startup parameter

**Comment by redbox2000** [comment]
Hi  
Sorry our varnish is version 3. 
when I try the varnishhoststat for v3 it works fine!

Thanks for quick response!
